version: '3.7'

services:
  app:
    build:
      dockerfile: docker/php/php-dev.Dockerfile
      context: .
    volumes:
      - '.:/var/www/app'
      - './docker/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_ENV: ${APP_ENV}
#    ports:
#      - '8080:8080'

  database:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  webserver:
    image: 'nginx:alpine'
    volumes:
      - './:/var/www/app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
